### ISSUE TITLE
Code rebuilding unnecessarily

### ISSUE THREAD

**Issue by sharpplayer** [rgoldberg/gradle-java-modules#13]
I get this error in all my projects that use the plugin:

Task ':myproject:compileJava' is not up-to-date because:
  Task ':myproject:compileJava' has an additional action that was implemented by the Java lambda 'org.gradle.java.taskconfigurer.JavaCompileTaskConfigurer$$Lambda$238/0x0000000100779840'. Using Java lambdas is not supported, use an (anonymous) inner class instead. 

This causes up-to-date projects to be considered not up-to-date and everything rebuilds.  I am not really sure what this error could mean, but could it be some unhappiness on Gradle (5)'s part with the plugin?

**Comment by rgoldberg** [comment]
Can you provide a stacktrace? (I’m not sure if you’ll actually get one for this if you use `—stacktrace`)

Does this also occur on Gradle 4.10.2?

**Comment by rgoldberg** [comment]
At what logging level is that output?

**Comment by sharpplayer** [comment]
You can see the error at -i level output.  -d didn't give any more information, sadly.

**Comment by rgoldberg** [comment]
I'm not seeing this issue on 4.1.0.2 at `-i` or `-d` for my project.  Maybe it's a Gradle 5.0 issue.  Can you try 4.10.2?

**Comment by sharpplayer** [comment]
It looks like it is a gradle 5 issue, which is a possibly a surprise as I could not see why it would be supported at 4 and not at 5

**Comment by sharpplayer** [comment]
Unless 5 has a bug!

**Comment by sharpplayer** [comment]
I will fight on with 4.10.2, but I suspect I will hit the old problems later with other Gradle bugs.

**Comment by rgoldberg** [comment]
@sharpplayer Is this issue still occurring? Thanks.

**Comment by sharpplayer** [comment]
Sadly, due to issues with using some of the auto modules in IntelliJ and Eclipse we gave up on modularisation of our code.  I suspect we may review this at some time in the future and come back to this plugin again, when we start using some of the later releases of the libraries we use.

**Comment by rgoldberg** [comment]
@sharpplayer 
Sorry to bother you, but, if you have time, could you sync your fork with this repo?  (If so, please remember to sync all 3 branches)

Or, better yet, if you don't need your fork, could you delete it?

This would be useful so that github staff can clear the git cache of the fork network of this plugin, which will remove some obsolete commit references from related github issues.  e.g., the first commit reference in the following issue isn't able to be pruned as long as your fork refers to to it:

https://github.com/gradle/gradle-java-modules/issues/19

Deleting or syncing your fork will remove the references.  Deleting is better because, if I ever rebase again, obsolete commits will still reside in your fork, necessitating further fork syncs.

I only ask this because I want to submit a lot of PRs to the official upstream Gradle plugin (https://github.com/gradle/gradle-java-modules), and I want to make things as simple as possible for the Gradle team to review & merge everything (which is also why I've been rebasing; I don't want the Gradle team to have to read code changes that don't linearly contribute to the final state of the code).

Thanks.

**Comment by sharpplayer** [comment]
Hopefully I have deleted the fork, so you shouldn't have problems now.
